import 'package:dead_or_alive/features/nine_judges/admin/models/playtest_record.dart';
import 'package:dead_or_alive/features/nine_judges/logging/game_log_models.dart';

/// Shared builder for admin-dashboard tests: fills in every GameSession
/// field the aggregation/list code reads, defaulting the rest, so each test
/// only spells out what it actually varies.
PlaytestRecord buildRecord({
  String gameId = 'g1',
  String? testerId = 'tester-1',
  int? playNumber = 1,
  bool? isFirstGame = true,
  String winner = 'savior',
  String playerFaction = 'savior',
  String cpuFaction = 'executor',
  String firstPlayer = 'savior',
  String cpuDifficulty = 'balanced',
  int totalTurns = 20,
  int? saviorScore = 25,
  int? executorScore = 20,
  DateTime? startedAt,
  DateTime? finishedAt,
  String rulesVersion = '1.2',
  String gameVersion = '1.3.0-external-test-beta',
  int? funRating,
  int? readingRating,
  int? luckRating,
  int? tempoRating,
  int? eyeChoiceRating,
  int? ruleUnderstandingRating,
  int? judgeUsefulnessRating,
  int? eyeTensionRating,
  int? strategicDepthRating,
  int? replayIntentRating,
  String? feedbackComment,
  String notes = '',
  bool? gameAbandoned,
  bool? saviorSpecialVerdictUsed,
  bool? executorSpecialVerdictUsed,
  int? judgeOpportunityCountSavior,
  int? judgeOpportunityCountExecutor,
  int? maxVisibleBonusWhileJudgeAvailableSavior,
  int? maxVisibleBonusWhileJudgeAvailableExecutor,
  bool? saviorReverseActionUsed,
  bool? executorReverseActionUsed,
  List<GameActionLog> actions = const [],
  bool actionsLoaded = false,
  String firebaseUid = 'uid-1',
}) {
  final started = startedAt ?? DateTime(2026, 1, 1, 10);
  final session = GameSession(
    gameId: gameId,
    startedAt: started,
    finishedAt: finishedAt ?? started.add(const Duration(minutes: 12)),
    gameVersion: gameVersion,
    rulesVersion: rulesVersion,
    mode: 'cpu',
    playerFaction: playerFaction,
    cpuFaction: cpuFaction,
    firstPlayer: firstPlayer,
    cpuDifficulty: cpuDifficulty,
    seed: 1,
    initialBoard: const [],
    winner: winner,
    saviorScore: saviorScore,
    executorScore: executorScore,
    totalTurns: totalTurns,
    testerId: testerId,
    playNumber: playNumber,
    isFirstGame: isFirstGame,
    funRating: funRating,
    readingRating: readingRating,
    luckRating: luckRating,
    tempoRating: tempoRating,
    eyeChoiceRating: eyeChoiceRating,
    ruleUnderstandingRating: ruleUnderstandingRating,
    judgeUsefulnessRating: judgeUsefulnessRating,
    eyeTensionRating: eyeTensionRating,
    strategicDepthRating: strategicDepthRating,
    replayIntentRating: replayIntentRating,
    feedbackComment: feedbackComment,
    notes: notes,
    gameAbandoned: gameAbandoned,
    saviorSpecialVerdictUsed: saviorSpecialVerdictUsed,
    executorSpecialVerdictUsed: executorSpecialVerdictUsed,
    judgeOpportunityCountSavior: judgeOpportunityCountSavior,
    judgeOpportunityCountExecutor: judgeOpportunityCountExecutor,
    maxVisibleBonusWhileJudgeAvailableSavior: maxVisibleBonusWhileJudgeAvailableSavior,
    maxVisibleBonusWhileJudgeAvailableExecutor: maxVisibleBonusWhileJudgeAvailableExecutor,
    saviorReverseActionUsed: saviorReverseActionUsed,
    executorReverseActionUsed: executorReverseActionUsed,
    actions: actions,
  );
  return PlaytestRecord(
    session: session,
    firebaseUid: firebaseUid,
    createdAt: started,
    actions: actionsLoaded ? actions : null,
  );
}

GameActionLog buildAction({
  int actionIndex = 0,
  int turnNumber = 1,
  String actingPlayer = 'player',
  String faction = 'savior',
  String actionType = 'eye',
  String targetPersonId = 'p1',
  int targetRank = 1,
  String actualTargetAttribute = 'good',
  String stateBefore = 'alive',
  String stateAfter = 'alive',
  int? turnDecisionTimeMs,
  int? eyeCandidateCount,
  bool wasReverseAction = false,
}) => GameActionLog(
  actionIndex: actionIndex,
  turnNumber: turnNumber,
  actingPlayer: actingPlayer,
  faction: faction,
  actionType: actionType,
  targetPersonId: targetPersonId,
  targetRank: targetRank,
  visibleTargetAttributeAtTime: null,
  actualTargetAttribute: actualTargetAttribute,
  stateBefore: stateBefore,
  stateAfter: stateAfter,
  lifeShieldBefore: false,
  lifeShieldAfter: false,
  judgedBefore: false,
  judgedAfter: false,
  actorHandBefore: const {},
  actorHandAfter: const {},
  opponentHandBefore: const {},
  opponentHandAfter: const {},
  timestamp: DateTime(2026, 1, 1),
  turnDecisionTimeMs: turnDecisionTimeMs,
  eyeCandidateCount: eyeCandidateCount,
  wasReverseAction: wasReverseAction,
);
