// File generated by hand from the Firebase console's Web app config
// (Project Settings > General > Your apps > Web app), in the same shape
// the FlutterFire CLI (`flutterfire configure`) would produce.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
      case TargetPlatform.iOS:
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have only been configured for web so far. '
          'Run `flutterfire configure` again to add this platform, or add '
          'its options here once it has its own Firebase app registered.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDC6CiUOgaxt2MxgJ3NDDfU9KSopndUiDU',
    appId: '1:263458911880:web:9f95fd976b8571a975113d',
    messagingSenderId: '263458911880',
    projectId: 'nine-verdicts',
    authDomain: 'nine-verdicts.firebaseapp.com',
    storageBucket: 'nine-verdicts.firebasestorage.app',
    measurementId: 'G-5TQJFG6XYP',
  );
}
